### ISSUE TITLE
Possibility to import CSV files

### ISSUE THREAD

**Issue by Novecento99** [ChonkyYoshi/python-tmx#3]
Hi,
I need to save a list of translations saved as a csv

To my understanding, is it not possibile yet to import it with this library right? 

thankyou!
(e grazie)

**Comment by ChonkyYoshi** [comment]
I'll add csv support as feature in the future, but the main focus right now is to improve the performance and reliability of the code before adding new features.

Assuming your csv doesn't have any tags, you can always create a new tmx object, iterate over your csv file and add a tu for every row and add a tuv for each value in that row

**Comment by ChonkyYoshi** [comment]
@Novecento99 
the newest release now includes basic csv support.
You can now import from a csv and export a Tmx object to a csv file.

Note that it uses some default info in the header so you can import from a csv export to a tmx file in one go. if you want different info in the header you can also use a Header object from your creation.
